### ISSUE TITLE
Amazing work

### ISSUE THREAD

**Issue by switchzts** [facebookresearch/SING#2]
Does it work on TTS task?Have you guys try to use it on TTS task?How it performence compare to Wavenet?

**Comment by adefossez** [comment]
Hi @switchzts, thanks for your interest in SING.
We have not tried TTS using SING but I believe it could be made to work. Replacing the music note to generate by a word to pronounce would be relatively straightforward. Generating a complete sentence would require more experimentations and tweaking at the current stage of the project.
Cheers
