### ISSUE TITLE
checkpoin link

### ISSUE THREAD

**Issue by yhgon** [facebookresearch/SING#4]
Dear team, 

could not download official checkpoint file. plz check the [Link](https://s3.amazonaws.com/sing-models/sing.th) . 

I want to compare my checkpoint with(50 epoch ae, 20 epoch se with large batch 2048) 
```
[train_ae][049] 100.0%, loss 0.028624 
[train_seq][049] 100.0%, loss 0.001227    
[train_sing][019] 100.0%, loss 0.052460 
```

AWS errors below : 
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>sing.th</Key>
<RequestId>42559F2F2BEA7254</RequestId>
<HostId>
asL1KRjG1jxIOkAGzounrqI5XZ9SAfa4W+7Q+d0/hHE1kw6DIj+iPRWCp4EzYG0cMrNJb2ZARiA=
</HostId>
</Error>
```

**Comment by adefossez** [comment]
Thanks for your report @yhgon , the link is fixed now :)
