### ISSUE TITLE
404 Not Found: When download the pretrained model

### ISSUE THREAD

**Issue by orrimoch** [facebookresearch/SING#5]
Hi,

When I try to download the pretrianed model (directly / by command)
I get Error: 404 Not Found

Thanks,
Or

**Comment by manolisp** [comment]
Hi,
When I try to downloa the pretrained model I get this response
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>sing-models</BucketName><RequestId>DE87BB8A2FA2FC24</RequestId><HostId></HostId></Error>

Thanks,
Manolis

**Comment by adefossez** [comment]
Fixed in https://github.com/facebookresearch/SING/commit/b46849a8d0854ae277c8c33fc9146a5d2ac6354b
Sorry about that guys ! It should work if you update the repo and retry :)

**Comment by orrimoch** [comment]
Hi @adefossez , it works!
By the way, Great paper!
My Thesis is in similar domain (Synthesizer).
Thanks for your help,
Or Rimoch
