### ISSUE TITLE
CUDA Out of memory

### ISSUE THREAD

**Issue by manolisp** [facebookresearch/SING#6]
Hi,
I 'm trying to run the training in my workstation with the following command
D:\SING>python -m sing.train --cuda --data nsynth/nsynth-test --output models/sing-test.th --l1 --batch-size 32
and I get this Out of memory error:
ConvolutionalAE(encoder=ConvolutionalEncoder(Sequential(
  (0): WindowedConv1d(window=hann**2,conv=Conv1d(1, 4096, kernel_size=(1024,), stride=(256,)))
  (1): ReLU()
  (2): Conv1d(4096, 4096, kernel_size=(1,), stride=(1,))
  (3): ReLU()
  (4): Conv1d(4096, 4096, kernel_size=(1,), stride=(1,))
  (5): ReLU()
  (6): Conv1d(4096, 128, kernel_size=(1,), stride=(1,))
)),decoder=ConvolutionalDecoder(Sequential(
  (0): Conv1d(128, 4096, kernel_size=(9,), stride=(1,))
  (1): ReLU()
  (2): Conv1d(4096, 4096, kernel_size=(1,), stride=(1,))
  (3): ReLU()
  (4): Conv1d(4096, 4096, kernel_size=(1,), stride=(1,))
  (5): ReLU()
  (6): WindowedConvTranpose1d(window=hann**2,conv_tr=ConvTranspose1d(4096, 1, kernel_size=(1024,), stride=(256,), padding=(768,)))
)))
Training autoencoder
  1%|▊                                                                               | 32/3280 [00:07<11:54,  4.54ex/s]
Traceback (most recent call last):
  File "C:\Users\Legion\Anaconda3\envs\tf-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Legion\Anaconda3\envs\tf-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\SING\sing\train.py", line 185, in <module>
    main()
  File "D:\SING\sing\train.py", line 176, in main
    autoencoder = train_autoencoder(args, **kwargs)
  File "D:\SING\sing\train.py", line 46, in train_autoencoder
    **kwargs).train()
  File "D:\SING\sing\fondation\trainer.py", line 175, in train
    self._train_epoch(self.train_dataset, epoch)
  File "D:\SING\sing\fondation\trainer.py", line 102, in _train_epoch
    total_loss += self._train_batch(batch)
  File "D:\SING\sing\ae\trainer.py", line 20, in _train_batch
    loss = self.train_loss(rebuilt, target)
  File "C:\Users\Legion\Anaconda3\envs\tf-gpu\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\SING\sing\dsp.py", line 100, in forward
    spec_a = self._log_spectrogram(a)
  File "D:\SING\sing\dsp.py", line 97, in _log_spectrogram
    return torch.log(self.epsilon + power(self.stft.forward(signal)))
  File "D:\SING\sing\dsp.py", line 76, in forward
    center=False)
  File "C:\Users\Legion\Anaconda3\envs\tf-gpu\lib\site-packages\torch\functional.py", line 417, in stft
    return torch._C._VariableFunctions.stft(input, n_fft, hop_length, win_length, window, normalized, onesided)
RuntimeError: CUDA out of memory. Tried to allocate 31.50 MiB (GPU 0; 4.00 GiB total capacity; 2.82 GiB already allocated; 9.10 MiB free; 99.85 MiB cached)

Can you provide any guidance how to handle this? I 've tried to lower the batch size to 32 without success.
Thanks in advance,
Manolis Poulakis

**Comment by adefossez** [comment]
Hi Manolis,
With 4GB of memory on your gpu you should reduce even further the batch size. 4 should work (on my gpu it is using less than 3 GB). Also make sure that no other process is using any memory (for instance running jupyter notebooks etc).

It is also possible to use a thinner version of the model, by reducing the number of channels in the convolution layers or the hidden units in the LSTM, for instance:

```
python3 -m sing.train --batch-size 32 --cuda --ae-channels 2048 --seq-hidden-size 512
```

I don't have the numbers around anymore but in my memory quality will be a bit worse but it still works reasonably well.
Cheers
Alexandre

**Comment by adefossez** [comment]
Closing the issue.
